import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import { AppLayout } from "@/components/layouts/app-layout";

const font = Cairo({
  variable: "--font-cairo-sans",
  weight: "variable",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.variable} antialiased`}>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
